docker-sign-in: &docker-sign-in
  name: login to doker remote
  command: |
    docker login \
      --username $DOCKER_USER \
      --password $DOCKER_PASS

mapping-var-env: &mapping-var-env
  name: define var with branch
  command: |
    case "$CIRCLE_BRANCH" in
      "master") ENV=prod
        ;;
      "release") ENV=next
        ;;
      "develop") ENV=staging
        ;;
      *) ENV=dev_$(echo "$CIRCLE_BRANCH" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
        ;;
    esac
    echo 'export ENV='$ENV >> $BASH_ENV

version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

jobs:
  build_and_push:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys
      - run: *mapping-var-env
      - run: *docker-sign-in
      - run:
          name: backup previous image
          command: |
            if export DOCKER_CLI_EXPERIMENTAL=enabled && docker manifest inspect "bimdata/design:prev-$ENV" > /dev/null; then
              docker pull "bimdata/design:$ENV"
              docker image tag "bimdata/design:$ENV" "bimdata/design:prev-$ENV"
              docker push "bimdata/design:prev-$ENV"
            fi
      - run:
          name: build docker image
          command: |
            echo $CIRCLE_SHA1 > VERSION
            docker build --tag "bimdata/design:$ENV" .
      - run:
          name: push new image
          command: docker push "bimdata/design:$ENV"
      - run:
          name: push latest tag image
          command: |
            if [[ "$CIRCLE_BRANCH" == "develop" ]]; then
              docker tag "bimdata/design:$ENV" bimdata/design:latest
              docker push bimdata/design:latest
            fi

  deploy:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: *docker-sign-in
      - run: *mapping-var-env
      - run:
          name: ansible deployment
          command: |
            docker run -e ANSIBLE_VAULT_PASSWD bimdata/deployment:latest \
              ansible-playbook \
              --inventory-file inventories/$ENV \
              --tags design \
              --extra-vars "ansible_ssh_private_key_file=./files/deploy_rsa" \
              --user deploy  \
              deploy.yml

workflows:
  test_and_deploy:
    jobs:
      - deploy_docker_dev:
          type: approval
          filters:
            branches:
              ignore:
                - master
                - release
                - develop
      - build_and_push:
          filters:
            branches:
              only:
                - master
                - release
                - develop
      - deploy:
          requires:
            - build_and_push
      - build_and_push:
          name: build_and_push_docker_dev
          requires:
            - deploy_docker_dev
