version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: /home/circleci/repo
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -f etc/Dockerfile -t bimdata/design:latest .
      - run:
          name: push to docker hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push bimdata/design:latest
              # deploy master branch
              docker exec -e ANSIBLE_VAULT_PASSWD -it deployment ansible-playbook deploy.yml -i inventories/staging --tags=design --extra-vars "ansible_ssh_private_key_file=./files/deploy_rsa" --user=deploy
            fi
