docker-sign-in: &docker-sign-in
  name: login to doker remote
  command: |
    docker login \
      --username $DOCKER_USER \
      --password $DOCKER_PASS \
      https://docker-registry.bimdata.io

mapping-var-env: &mapping-var-env
  name: define var with branch
  command: |
    case "$CIRCLE_BRANCH" in
      "master") ENV=prod; TAG=prod
        ;;
      "release") ENV=next; TAG=next
        ;;
      "develop") ENV=staging; TAG=staging
        ;;
      *) ENV=dev; TAG=dev_$(echo "$CIRCLE_BRANCH" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
        ;;
    esac
    echo 'export ENV='$ENV >> $BASH_ENV
    echo 'export TAG='$TAG >> $BASH_ENV

version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

jobs:
  build_and_push:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys
      - run: *mapping-var-env
      - run: *docker-sign-in
      - run:
          name: backup previous image
          command: |
            if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect "docker-registry.bimdata.io/bimdata/design:$TAG" > /dev/null; then
              docker pull "docker-registry.bimdata.io/bimdata/design:$TAG"
              docker image tag "docker-registry.bimdata.io/bimdata/design:$TAG" "docker-registry.bimdata.io/bimdata/design:prev-$TAG"
              docker push "docker-registry.bimdata.io/bimdata/design:prev-$TAG"
            fi
      - run:
          name: build docker image
          command: |
            echo $CIRCLE_SHA1 > VERSION
            docker build --tag "docker-registry.bimdata.io/bimdata/design:$TAG" --file etc/Dockerfile .
      - run:
          name: push new image
          command: docker push "docker-registry.bimdata.io/bimdata/design:$TAG"
      - run:
          name: push latest tag image
          command: |
            if [[ "$CIRCLE_BRANCH" == "develop" ]]; then
              docker tag "docker-registry.bimdata.io/bimdata/design:$TAG" docker-registry.bimdata.io/bimdata/design:latest
              docker push docker-registry.bimdata.io/bimdata/design:latest
            fi

  deploy:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: *docker-sign-in
      - run: *mapping-var-env
      - run:
          name: ansible deployment
          command: |
            docker run -e ANSIBLE_VAULT_PASSWD docker-registry.bimdata.io/bimdata/deployment:latest \
              ansible-playbook \
              --inventory-file inventories/$ENV \
              --tags design \
              --extra-vars "{\"ansible_ssh_private_key_file\":\"./files/deploy_rsa\",\"ops_env\":\"$TAG\"}" \
              --user deploy  \
              deploy.yml
      - run:
          name: display url
          command: |
            echo "The new build is available on :"
            if [ "$ENV" = "prod" ]; then echo "https://design.bimdata.io"; else echo "http://design-$TAG.bimdata.io"; fi

workflows:
  test_and_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - master
                - release
                - develop
      - deploy:
          requires:
            - build_and_push
